---
title: "Model"
execute:
  echo: false
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(primer.data)
library(brms)
library(tidybayes)
library(gtsummary)
library(stringr)
```

```{r}
#| label: data
x <- read.csv("West_Midlands_Crime.csv")
set.seed(123)
crime <- x |> sample_frac(.10) |> 
  mutate(type = as.factor(Crime.type), outcome = Last.outcome.category, area = LSOA.name)|> filter(outcome != "")
crime <- crime |> mutate(SuspectIdentified = ifelse(outcome %in% c(
    "Offender given a caution",
    "Awaiting court outcome", 
    "Action to be taken by another organisation", 
    "Awaiting court outcome",
"Formal action is not in the public interest",
"Further action is not in the public interest"), 1, 0)) |> 
  select(SuspectIdentified, type, area)
```

```{r}
ndata <- tibble(type = c( "Bicycle theft",
 "Burglary", 
 "Criminal damage and arson", 
                      "Drugs",
                 "Other crime", "Other theft", 
                      "Possession of weapons",  
                 "Public order",  
                     "Robbery",
                 "Shoplifting",  
       "Theft from the person",
               "Vehicle crime", "Violence and sexual offences"))
```

$$
\text{SuspectIdentified}_i = \beta_0 + \beta_1 \cdot \text{type}_i + \epsilon_i
$$
```{r}
#| cache: true
#| label: model
#| warning: false
fit <- brm(formula = SuspectIdentified ~ type,
           data = crime,
           family = bernoulli(),
           iter = 1200,
           warmup = 600,
           chains = 2,
           refresh = 0,
           silent = 2,
           seed = 99)
```

```{r}
tbl_regression(fit)
```

